package com.kotlin.openweatherapp.util

const val ABSOLUTE_ZERO = 273.15

const val LOCATION_TYPE_CURRENT = 1002
const val LOCATION_TYPE_CHOSEN = 1001
const val LOCATION_TYPE = "LOCATION_TYPE"
const val LOCATION_TYPE_DEFAULT = 999
const val LOCATION_CITY_NAME =  "City_Name"
const val LOCATION_CITY_LAT = "City_Lat"
const val LOCATION_CITY_LON = "City_Lon"

const val LOCATION_PERMISSIONS_REQUEST_CODE = 9001

const val GPS_SETTINGS_STATUS_CHANGE_REQUEST_CODE = 1234

const val LOCATION_NOT_YET_SELECTED_REQUEST_CODE = 133